// Code generated by protoc-gen-go.
// source: kyc.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	kyc.proto

It has these top-level messages:
	Record
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Response_Match int32

const (
	Response_NOENTRY Response_Match = 0
	Response_MATCH   Response_Match = 1
	Response_NOMATCH Response_Match = 2
)

var Response_Match_name = map[int32]string{
	0: "NOENTRY",
	1: "MATCH",
	2: "NOMATCH",
}
var Response_Match_value = map[string]int32{
	"NOENTRY": 0,
	"MATCH":   1,
	"NOMATCH": 2,
}

func (x Response_Match) String() string {
	return proto1.EnumName(Response_Match_name, int32(x))
}

type Record struct {
	Nric    string `protobuf:"bytes,1,opt,name=Nric" json:"Nric,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address" json:"Address,omitempty"`
	Mobile  string `protobuf:"bytes,4,opt,name=Mobile" json:"Mobile,omitempty"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto1.CompactTextString(m) }
func (*Record) ProtoMessage()    {}

type Response struct {
	Nric    Response_Match `protobuf:"varint,1,opt,name=Nric,enum=proto.Response_Match" json:"Nric,omitempty"`
	Name    Response_Match `protobuf:"varint,2,opt,name=Name,enum=proto.Response_Match" json:"Name,omitempty"`
	Address Response_Match `protobuf:"varint,3,opt,name=Address,enum=proto.Response_Match" json:"Address,omitempty"`
	Mobile  Response_Match `protobuf:"varint,4,opt,name=Mobile,enum=proto.Response_Match" json:"Mobile,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func init() {
	proto1.RegisterEnum("proto.Response_Match", Response_Match_name, Response_Match_value)
}
